openapi: '3.0.2'
info:
  title: Test with terraform
  version: '0.1'


paths:
  /tests:
    get:
      description: "Echo response"
      operationId: Echo
      responses:
        '200':
          description: OK