openapi: 3.0.1
info:
  title: APIM Function App Hello World
  version: '1.0'
servers:
  - url: https://testwill-dev-api-mngmnt-apim.azure-api.net/api/hello_world
paths:
  /helloWorld:
    get:
      summary: HelloWorldFn
      operationId: get-hello-world
      responses:
        '200':
          description:
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]